// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsSite.Infrastructure.DatabaseContext;

#nullable disable

namespace NewsSite.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230923145709_ArticlesTableUpdate")]
    partial class ArticlesTableUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewsSite.Core.Domain.Models.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12c1ff9c-c582-45b0-83b8-5c9d3faf019c"),
                            Author = "Author 1",
                            Body = "This is the body of article 1",
                            DatePublished = new DateTime(2023, 9, 23, 16, 57, 9, 12, DateTimeKind.Local).AddTicks(7609),
                            PreviewText = "This is the preview text of article 1",
                            Title = "Article 1"
                        },
                        new
                        {
                            Id = new Guid("9c01c167-b5c4-42fb-97f0-af34fc6f6e7f"),
                            Author = "Author 2",
                            Body = "This is the body of article 2",
                            DatePublished = new DateTime(2023, 9, 23, 16, 57, 9, 12, DateTimeKind.Local).AddTicks(7683),
                            PreviewText = "This is the preview text of article 2",
                            Title = "Article 2"
                        },
                        new
                        {
                            Id = new Guid("cf1664f0-16e6-4c8c-8eaf-699e3160f9ef"),
                            Author = "Author 3",
                            Body = "This is the body of article 3",
                            DatePublished = new DateTime(2023, 9, 23, 16, 57, 9, 12, DateTimeKind.Local).AddTicks(7688),
                            PreviewText = "This is the preview text of article 3",
                            Title = "Article 3"
                        },
                        new
                        {
                            Id = new Guid("021a6a5e-f59b-4d64-8bf5-9461faffabd2"),
                            Author = "Author 4",
                            Body = "This is the body of article 4",
                            DatePublished = new DateTime(2023, 9, 23, 16, 57, 9, 12, DateTimeKind.Local).AddTicks(7766),
                            PreviewText = "This is the preview text of article 4",
                            Title = "Article 4"
                        },
                        new
                        {
                            Id = new Guid("0667b7d1-e4c1-4872-abb0-03a2a0301950"),
                            Author = "Author 5",
                            Body = "This is the body of article 5",
                            DatePublished = new DateTime(2023, 9, 23, 16, 57, 9, 12, DateTimeKind.Local).AddTicks(7793),
                            PreviewText = "This is the preview text of article 5",
                            Title = "Article 5"
                        },
                        new
                        {
                            Id = new Guid("a9fd0c91-dd88-4187-8cd6-9f2f20b2a050"),
                            Author = "Author 6",
                            Body = "This is the body of article 6",
                            DatePublished = new DateTime(2023, 9, 23, 16, 57, 9, 12, DateTimeKind.Local).AddTicks(7798),
                            PreviewText = "This is the preview text of article 6",
                            Title = "Article 6"
                        },
                        new
                        {
                            Id = new Guid("789808fd-c124-4d83-897b-1b9823339574"),
                            Author = "Author 7",
                            Body = "This is the body of article 7",
                            DatePublished = new DateTime(2023, 9, 23, 16, 57, 9, 12, DateTimeKind.Local).AddTicks(7802),
                            PreviewText = "This is the preview text of article 7",
                            Title = "Article 7"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
